security:
    role_hierarchy:
        ROLE_USER:
            - CONTROLLER_APP_DASHBOARD
        ROLE_REPORT:
            - CONTROLLER_APP_RAPPORTAGES
            - CONTROLLER_APP_DOELSTELLINGEN
            - ROLE_INLOOP_SCHORSINGEN
            - ROLE_INLOOP_REPORTS
        ROLE_DOELSTELLING_BEHEER: []
        ROLE_PORTIER:
            - ROLE_INLOOP_REGISTRATIES
            - ROLE_INLOOP_OPMERKINGEN
        ROLE_INLOOP: []
        ROLE_INLOOP_INTAKES:
            - ROLE_INLOOP
            - ROLE_INLOOP_KLANTEN
        ROLE_INLOOP_OPMERKINGEN:
            - ROLE_INLOOP
        ROLE_INLOOP_REGISTRATIES:
            - ROLE_INLOOP
        ROLE_INLOOP_REPORTS:
            - ROLE_INLOOP
        ROLE_INLOOP_SCHORSINGEN:
            - ROLE_INLOOP
        ROLE_INLOOP_VRIJWILLIGERS:
            - ROLE_INLOOP
            - CONTROLLER_APP_VRIJWILLIGERS
        ROLE_INLOOP_BEHEER:
            - ROLE_INLOOP
            - ROLE_INLOOP_INTAKES
            - ROLE_INLOOP_KLANTEN
            - ROLE_INLOOP_OPMERKINGEN
            - ROLE_INLOOP_REGISTRATIES
            - ROLE_INLOOP_REPORTS
            - ROLE_INLOOP_SCHORSINGEN
            - ROLE_INLOOP_VRIJWILLIGERS
        ROLE_INLOOP_DAGCOORDINATOR:
            - ROLE_INLOOP_INTAKES
            - ROLE_INLOOP_REGISTRATIES
            - ROLE_INLOOP_SCHORSINGEN
            - ROLE_INLOOP_OPMERKINGEN
        ROLE_INLOOP_TEAMLEIDERS:
            - ROLE_INLOOP_DAGCOORDINATOR
        ROLE_MLO:
            - CONTROLLER_APP_KLANTEN
            - CONTROLLER_APP_VRIJWILLIGERS
            - CONTROLLER_APP_ZRMS
            - ROLE_INLOOP_INTAKES
            - ROLE_INLOOP_REGISTRATIES
            - ROLE_INLOOP_SCHORSINGEN
            - ROLE_INLOOP_OPMERKINGEN
        ROLE_OEKRAINE:
            - CONTROLLER_APP_KLANTEN
        ROLE_OEKRAINE_LOCATIEHOOFD:
            - ROLE_OEKRAINE
        ROLE_OEKRAINE_BEHEER:
            - ROLE OEKRAINE
            - ROLE_OEKRAINE_LOCATIEHOOFD
        ROLE_MW:
            - CONTROLLER_APP_KLANTEN
            - CONTROLLER_APP_RAPPORTAGES
            - CONTROLLER_APP_DOELSTELLINGEN
            - CONTROLLER_APP_ZRMS
            - CONTROLLER_ATTACHMENTS
        ROLE_VOLUNTEERS:
            - ROLE_INLOOP_REGISTRATIES
        ROLE_STAGE:
            - CONTROLLER_APP_KLANTEN
            - CONTROLLER_APP_ZRMS
            - ROLE_INLOOP_INTAKES
            - ROLE_INLOOP_REGISTRATIES
            - ROLE_INLOOP_OPMERKINGEN
            - ROLE_INLOOP_SCHORSINGEN
            - ROLE_USER
        ROLE_PFO_BEPERKT: []
        ROLE_PFO_BEHEER: []
        ROLE_PFO:
            - ROLE_PFO_BEHEER #andersom geredeneerd. Historisch zo gegegroeid. Beheer is om consistent te zijn met de rest van ECD.
        ROLE_TEAMLEIDERS:
            - ROLE_GA
            - ROLE_MW
            - ROLE_MW_BEHEER
            - ROLE_INLOOP_INTAKES
            - ROLE_INLOOP_OPMERKINGEN
            - ROLE_INLOOP_REGISTRATIES
            - ROLE_INLOOP_REPORTS
            - ROLE_INLOOP_SCHORSINGEN
            - ROLE_INLOOP_VRIJWILLIGERS
            - ROLE_INLOOP_BEHEER
            - CONTROLLER_ADMIN
            - ROLE_SECRETARIAAT
            - CONTROLLER_APP_KLANTEN
            - CONTROLLER_APP_RAPPORTAGES
            - CONTROLLER_APP_DOELSTELLINGEN
            - CONTROLLER_APP_ZRMS
            - CONTROLLER_APP_VRIJWILLIGERS
            - CONTROLLER_ATTACHMENTS
        ROLE_IZ:
            - ROLE_EROPUIT
            - CONTROLLER_APP_KLANTEN
            - CONTROLLER_APP_VRIJWILLIGERS
            - CONTROLLER_APP_ZRMS
        ROLE_IZ_BEHEER:
            - ROLE_IZ
        ROLE_GA:
            - ROLE_EROPUIT
            - CONTROLLER_APP_KLANTEN
            - CONTROLLER_APP_VRIJWILLIGERS
            - CONTROLLER_ATTACHMENTS
        ROLE_GA_BEHEER:
            - ROLE_GA
            - ROLE_EROPUIT_BEHEER
        ROLE_CLIP: []
        ROLE_CLIP_BEHEER:
            - ROLE_CLIP
            - ROLE_CLIP_VRIJWILLIGERS
            - CONTROLLER_APP_VRIJWILLIGERS
        ROLE_DAGBESTEDING: []
        ROLE_DAGBESTEDING_BEHEER:
            - ROLE_DAGBESTEDING
        ROLE_HOMESERVICE:
            - CONTROLLER_APP_KLANTEN
            - CONTROLLER_APP_VRIJWILLIGERS
            - ROLE_HS
        ROLE_HOMESERVICE_BEHEER:
            - ROLE_HOMESERVICE
            - ROLE_HS_BEHEER
        ROLE_HS_BEHEER: [] #to be in line with the bundle naming...
        ROLE_HS: []
        ROLE_TW:
            - CONTROLLER_APP_KLANTEN
            - CONTROLLER_APP_VRIJWILLIGERS
            - ROLE_TW_VRIJWILLIGERS
        ROLE_TW_BEHEER:
            - ROLE_TW
        ROLE_TW2:
            - ROLE_TW2
        ROLE_TW_BEHEER2:
            - ROLE_TW_BEHEER
        ROLE_OEK: []
        ROLE_OEK_BEHEER:
            - ROLE_OEK
        ROLE_WERKBEGELEIDER: []
        ROLE_ADMINISTRATIEBEDRIJF:
            - ROLE_DOELSTELLING_BEHEER
            - ROLE_INLOOP_VRIJWILLIGERS
        ROLE_SCIP:
            - CONTROLLER_APP_KLANTEN
        ROLE_SCIP_BEHEER:
            - ROLE_SCIP
        ROLE_SKIP_BEHEER:
            - ROLE_SCIP_BEHEER
        ROLE_UHK:
            - CONTROLLER_APP_ZRMS
        ROLE_UHK_BEHEER:
            - ROLE_UHK
            - CONTROLLER_APP_KLANTEN
        ROLE_EROPUIT_BEHEER:
            - ROLE_EROPUIT
        ROLE_EROPUIT: []
        ROLE_BUURTBOERDERIJ:
            - CONTROLLER_APP_VRIJWILLIGERS
        ROLE_VILLA:
            - CONTROLLER_APP_VRIJWILLIGERS
        ROLE_HRM:
            - ROLE_USERADMIN
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_MW
            - ROLE_MW_BEHEER
            - ROLE_REPORT
            - ROLE_PORTIER
            - ROLE_MLO
            - ROLE_HI5
            - ROLE_CLIP
            - ROLE_CLIP_BEHEER
            - ROLE_DAGBESTEDING
            - ROLE_DAGBESTEDING_BEHEER
            - ROLE_EROPUIT
            - ROLE_HOMESERVICE
            - ROLE_HOMESERVICE_BEHEER
            - ROLE_TW
            - ROLE_TW_BEHEER
            - ROLE_OEK
            - ROLE_OEK_BEHEER
            - ROLE_OEKRAINE_BEHEER
            - ROLE_INLOOP
            - ROLE_INLOOP_BEHEER
            - ROLE_BACK_ON_TRACK_COORDINATOR
            - ROLE_BACK_ON_TRACK_COACH
            - ROLE_VOLUNTEERS
            - ROLE_STAGE
            - ROLE_PFO
            - ROLE_TRAJECTBEGELEIDER
            - ROLE_TEAMLEIDERS
            - ROLE_IZ
            - ROLE_IZ_BEHEER
            - ROLE_GA
            - ROLE_SCIP
            - ROLE_SCIP_BEHEER
            - ROLE_UHK
            - ROLE_UHK_BEHEER
            - CONTROLLER_ADMIN
            - CONTROLLER_APP_KLANTEN
            - CONTROLLER_APP_RAPPORTAGES
            - CONTROLLER_APP_DOELSTELLINGEN
            - CONTROLLER_APP_VRIJWILLIGERS
            - CONTROLLER_APP_ZRMS
            - CONTROLLER_MEDEWERKERS
            - CONTROLLER_APP_DOWNLOAD
            - ROLE_HRM
            - ROLE_BUURTBOERDERIJ
            - ROLE_SECRETARIAAT
            - ROLE_PROGRAMMACOORDINATOR
            - ROLE_MANAGEMENT
            - ROLE_SPORT
            - ROLE_VILLA
        CONTROLLER_APP_KLANTEN:
            - CONTROLLER_APP_DOCUMENTEN
        CONTROLLER_APP_VRIJWILLIGERS:
            - CONTROLLER_APP_DOCUMENTEN
        ROLE_PROGRAMMACOORDINATORA:
            - ROLE_PROGRAMMACOORDINATOR
        ROLE_PROGRAMMACOORDINATORB:
            - ROLE_PROGRAMMACOORDINATOR
        ROLE_PROGRAMMACOORDINATOR:
            - CONTROLLER_APP_DOELSTELLINGEN
        ROLE_MANAGEMENT:
            - CONTROLLER_APP_DOELSTELLINGEN
        ROLE_SECRETARIAAT:
            - ROLE_GLOBALDOWNLOAD
            - CONTROLLER_APP_KLANTEN
            - CONTROLLER_APP_VRIJWILLIGERS
        ROLE_GLOBALDOWNLOAD:
            - CONTROLLER_APP_DOWNLOAD


parameters:
    roles_groups:
        ROLE_ADMIN: "CN=ECD Admin,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_VOLUNTEERS: "CN=ECD Volunteers,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_STAGE: "CN=ECD Stage,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_PORTIER: "CN=ECD Inloop Portier,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_MLO: "CN=ECD MLO,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_INLOOP_VRIJWILLIGERS: "CN=ECD Inloop vrijwilliger,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_INLOOP_TEAMLEIDERS: "CN=ECD Inloop teamleider,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_INLOOP_DAGCOORDINATOR: "CN=ECD Inloop dagco,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_MW: "CN=ECD Maatschappelijk,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_MW_BEHEER: "CN=ECD MW Beheer,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_HI5: "CN=ECD Hi5,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_TRAJECTBEGELEIDER: "CN=ECD Trajectbegeleider,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_WERKBEGELEIDER: "CN=ECD Werkbegeleider,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_TEAMLEIDERS: "CN=ECD Teamleiders,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_PFO_BEPERKT: "CN=ECD PFO Beperkt,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_PFO: "CN=ECD PFO,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_BACK_ON_TRACK_COORDINATOR: "CN=ECD Back On Track Coordinator,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_BACK_ON_TRACK_COACH: "CN=ECD Back on Track Coach,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_GA: "CN=ECD Groepsactiviteit,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_GA_BEHEER: "CN=ECD Beheer Groepsactiviteit,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_IZ: "CN=ECD IZ,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_IZ_BEHEER: "CN=ECD IZ Beheer,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_REPORT: "CN=ECD Report,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_OEK: "CN=ECD Op Eigen Kracht,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_OEK_BEHEER: "CN=ECD Op Eigen Kracht Beheer,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_TW: "CN=ECD Onder de Pannen,CN=Users,DC=cluster,DC=deregenboog" #bw compatiblity
        ROLE_TW_BEHEER: "CN=ECD Onder de Pannen Beheer,CN=Users,DC=cluster,DC=deregenboog" #bw comp.
        ROLE_TW2: "CN=ECD Tijdelijk Wonen,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_TW_BEHEER2: "CN=ECD Tijdelijk Wonen Beheer,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_ADMINISTRATIEBEDRIJF: "CN=administratiebedrijf,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_DAGBESTEDING: "CN=ECD Trajectbegeleider,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_DAGBESTEDING_BEHEER: "CN=ECD Dagbesteding Beheer,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_CLIP: "CN=ECD CLIP,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_CLIP_BEHEER: "CN=ECD CLIP Beheer,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_HOMESERVICE: "CN=ECD Homeservice,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_HOMESERVICE_BEHEER: "CN=ECD Homeservice Beheer,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_SCIP: "CN=ECD SCIP,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_SCIP_BEHEER: "CN=ECD SCIP Beheer,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_SKIP_BEHEER: "CN=ECD SKIP Beheer,CN=Users,DC=cluster,DC=deregenboog" # because of typo in LDAP-group
        ROLE_EROPUIT: "CN=ECD ErOpUit,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_EROPUIT_BEHEER: "CN=ECD ErOpUit Beheer,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_BUURTBOERDERIJ: "CN=ECD Buurtboerderij,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_SECRETARIAAT: "CN=ECD Secretariaat,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_MANAGEMENT: "CN=ECD Management,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_PROGRAMMACOORDINATOR: "CN=ECD Programmacoordinator,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_PROGRAMMACOORDINATORA: "CN=ECD Programmaco√∂rdinator,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_PROGRAMMACOORDINATORB: "CN=ECD Programma Co\u00f6rdinator,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_UHK: "CN=ECD Uit het Krijt,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_UHK_BEHEER: "CN=ECD Uit het Krijt Beheer,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_SPORT: "CN=ECD Sport,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_VILLA: "CN=ECD Villa,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_HRM: "CN=ECD P&O,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_OEKRAINE: "CN=ECD Oekraine,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_OEKRAINE_LOCATIEHOOFD: "CN=ECD Oekraine Locatiehoofd,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_OEKRAINE_BEHEER: "CN=ECD Oekraine Beheer,CN=Users,DC=cluster,DC=deregenboog"
        ROLE_OEKRAINE_MW: "CN=ECD Oekraine Maatschappelijk werk,CN=Users,DC=cluster,DC=deregenboog"
