imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: nl_NL
    acl_disabled: false
    pagination.items_per_page: 20
    doctrine.orm.naming_strategy.default.class: AppBundle\Service\DoctrineOrmNamingStrategy

framework:
    default_locale: "%locale%"
    translator: { fallbacks: ["%locale%"] }
    secret: "%secret%"
    session:
        name: ECD
        cookie_lifetime: 86400 # 60*60*24
        save_path: '%kernel.root_dir%/../var/sessions'
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
#        - form_div_layout.html.twig
        - bootstrap_3_horizontal_layout.html.twig
    cache: '%kernel.cache_dir%/twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: "%database_driver%"
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: "utf8"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            string_functions:
                concat_ws: Luxifer\DQL\String\ConcatWs

jms_di_extra: ~

knp_paginator: ~

swiftmailer:
    transport: mail

assetic:
    debug: "%kernel.debug%"
    use_controller: "%kernel.debug%"
    filters:
        cssrewrite: ~

vich_uploader:
    db_driver: orm
    mappings:
        hs_document:
            namer: vich_uploader.namer_uniqid
            uri_prefix: /hs/documenten
            upload_destination: '%kernel.root_dir%/../archive/hs'
        odp_document:
            namer: vich_uploader.namer_uniqid
            uri_prefix: /odp/documenten/download
            upload_destination: '%kernel.root_dir%/../archive/odp'
