_app:
    resource: "@AppBundle/Resources/config/routing.yml"

_iz:
    resource: "@IzBundle/Resources/config/routing.yml"

_ga:
    resource: "@GaBundle/Resources/config/routing.yml"

_odp:
    resource: "@OdpBundle/Resources/config/routing.yml"

