_app:
    resource: "@AppBundle/Resources/config/routing.yml"

_iz:
    resource: "@IzBundle/Resources/config/routing.yml"

_hs:
    resource: "@HsBundle/Resources/config/routing.yml"

_oek:
    resource: "@OekBundle/Resources/config/routing.yml"
_odp:
    resource: "@OdpBundle/Resources/config/routing.yml"
