parameters:
    cake:
        email:
            prod:
                informele_zorg: "jschmidt@deregenboog.org"
                dagbesteding: "bnieuwburg@deregenboog.org"
                inloophuis: "adbruijn@deregenboog.org"
                hulpverlening: "jvloo@deregenboog.org"
                agressie: "tvhamond@deregenboog.org"
                administratiebedrijf: "administratiebedrijf@deregenboog.org"
            beta:
                informele_zorg: "jschmidt@deregenboog.org"
                dagbesteding: "bnieuwburg@deregenboog.org"
                inloophuis: "adbruijn@deregenboog.org"
                hulpverlening: "jvloo@deregenboog.org"
                agressie: "tvhamond@deregenboog.org"
                administratiebedrijf: "administratiebedrijf@deregenboog.org"
            test:
                informele_zorg: "bhuttinga@deregenboog.org"
                dagbesteding: "bhuttinga@deregenboog.org"
                inloophuis: "bhuttinga@deregenboog.org"
                hulpverlening: "bhuttinga@deregenboog.org"
                agressie: "bhuttinga@deregenboog.org"
                administratiebedrijf: "bhuttinga@deregenboog.org"

        debug_level: 2

        Config.language: dut

        Calendar.dateDisplayFormat: d-M-y

        volunteers:
            vrijwilliger_oud_west: 14
            vrijwilliger_eik: 9
            vrijwilliger_de_kloof: 10
            vrijwilliger_macom: 11
            vrijwilliger_macom_nacht: 12
            vwspreekbuis: 15

        ldap:
            groups:
                werkbegeleiders: 10195
                trajectbegeleiders: 10194

        ACL.groups:
            GROUP_ADMIN: 10105
            GROUP_DEVELOP: 10422
            GROUP_VOLONTEERS: 1025
            GROUP_STAGE: 1026
            GROUP_PORTIER: 10103
            GROUP_MLO: 10104
            GROUP_MAATSCHAPPELIJK: 10117
            GROUP_HI5: 10097
            GROUP_TRAJECTBEGELEIDER: 10194
            GROUP_WERKBEGELEIDER: 10195
            GROUP_TEAMLEIDERS: 10105
            GROUP_PFO: 10123
            GROUP_BACK_ON_TRACK_COORDINATOR: 10404
            GROUP_BACK_ON_TRACK_COACH: 10403
            GROUP_GROEPSACTIVITEIT: 10396
            GROUP_IZ: 10460
            GROUP_REPORT: 10570
            GROUP_IZ_BEHEER: 10462
            GROUP_BEHEER_GROEPSACTIVITEIT: 10463

        ACL.permissions:
            GROUP_REPORT:
                - Rapportages
            GROUP_PORTIER:
                - Registraties
                - Opmerkingen
            GROUP_MLO:
                - Intakes
                - Klanten
                - Registraties
                - Schorsingen
                - Opmerkingen
            GROUP_MAATSCHAPPELIJK:
                - Awbz
                - AwbzHoofdaannemers
                - AwbzIndicaties
                - AwbzIntakes
                - Intakes
                - Klanten
                - Registraties
                - Opmerkingen
                - MaatschappelijkWerk
                - Verslagen
                - Rapportages
                - Attachments
            GROUP_HI5:
                - Intakes
                - Klanten
                - Attachments
            GROUP_ADMIN:
                - Admin
                - Awbz
                - AwbzHoofdaannemers
                - AwbzIndicaties
                - AwbzIntakes
                - Intakes
                - Klanten
                - Hi5
                - MaatschappelijkWerk
                - Verslagen
                - Registraties
                - Schorsingen
                - Opmerkingen
                - Rapportages
                - MwInventarisaties
                - Attachments
                - BackOnTrack
                - BotVerslagen
                - Vrijwilligers
                - groepsactiviteiten_klanten
            GROUP_BACK_ON_TRACK_COORDINATOR:
                - BackOnTrack
                - BotVerslagen
                - BotKoppelingen
                - Intakes
            GROUP_BACK_ON_TRACK_COACH:
                - BackOnTrack
                - BotVerslagen
                - BotKoppelingen
            GROUP_VOLONTEERS:
                - Registraties
            GROUP_STAGE:
                - Intakes
                - Klanten
                - Registraties
            GROUP_PFO:
                - PfoClienten
                - PfoRapporten
                - PfoAardRelaties
                - PfoGroepen
                - PfoVerslagen
            GROUP_TRAJECTBEGELEIDER:
                - Awbz
                - AwbzHoofdaannemers
                - AwbzIndicaties
                - AwbzIntakes
                - Hi5
                - Attachments
            GROUP_IZ:
                - Klanten
                - Vrijwilligers
                - iz_klanten
                - IzDeelnemers
                - IzHulpvragen
                - IzHulpaanbiedingen
                - IzKoppelingen
                - IzRapportages
                - IzVerslagen
                - Attachments
                - odp
                - OdpBundle\Controller\Huurders
                - OdpBundle\Controller\Verhuurders
                - OdpBundle\Controller\Huurverzoeken
                - OdpBundle\Controller\Huuraanbiedingen
                - OdpBundle\Controller\Huurovereenkomsten
            GROUP_IZ_BEHEER:
                - IzAfsluitingen
                - iz_klanten
                - IzDeelnemers
                - IzHulpvragen
                - IzHulpaanbiedingen
                - IzKoppelingen
                - IzRapportages
                - IzEindekoppelingen
                - IzIntervisiegroepen
                - IzKoppelingen
                - IzOntstaan
                - IzProjecten
                - IzVerslagen
                - IzViaPersonen
                - IzVraagaanboden
                - IzOntstaanContacten
                - odp
                - OdpBundle\Controller\Huurders
                - OdpBundle\Controller\Verhuurders
                - OdpBundle\Controller\Huurverzoeken
                - OdpBundle\Controller\Huuraanbiedingen
                - OdpBundle\Controller\Huurovereenkomsten
                - OdpBundle\Controller\Coordinatoren
                - OdpBundle\Controller\Huurderafsluitingen
                - OdpBundle\Controller\Verhuurderafsluitingen
                - OdpBundle\Controller\Woningbouwcorporaties
            GROUP_GROEPSACTIVITEIT:
                - Klanten
                - Vrijwilligers
                - Attachments
                - groepsactiviteiten_klanten
                - groepsactiviteiten_vrijwilligers
                - GroepsactiviteitenIntakes
                - GroepsactiviteitenVerslagen
                - GroepsactiviteitenRapportages
            GROUP_BEHEER_GROEPSACTIVITEIT:
                - GroepsactiviteitenGroepen
                - GroepsactiviteitenRedenen
            GROUP_WERKBEGELEIDER: []
            GROUP_DEVELOP:
                - "*"
                - Klanten
                - Vrijwilligers
                - iz_klanten
                - IzDeelnemers
                - IzVerslagen
                - groepsactiviteiten_klanten

        all_menu_items:
            Hi5: Hi5
            Klanten: Klantenlijst
            Vrijwilligers: Vrijwilligers
            Registraties: Registratie
            MaatschappelijkWerk: Maatschappelijk werk
            Rapportages: Rapportages
            Awbz: AWBZ
            PfoClienten: PFO
            iz_klanten: IZ
            groepsactiviteiten_klanten: Groepsactiviteiten
            hs_klanten: HomeService
            oek: Op Eigen Kracht
            odp: Onder de Pannen
            Admin: Admin

        TBC_months_period: 6

        Landen.AMOC: [5002, 5009, 5010, 5015, 5017, 5039, 5040, 5049, 6002, 6003, 6007, 6018, 6029, 6037, 6039, 6066, 6067, 7003, 7024, 7028, 7044, 7047, 7050, 7064, 7065, 7066]

        options_medewerker:
            1: medewerker
            2: stagiair
            3: vrijwilliger

        Communicatietypen:
            iedereen: Iedereen
            communicatie_email: E-Mail
            communicatie_post: Post

        IzFase:
#            iedereen: Iedereen
            aanmelding: Aanmelding
            onvolledig: Onvolledige invoer
            wachtlijst: Wachtlijst
            gekoppeld: Gekoppeld
#            beeindigd: Beeindigd
            afgesloten: Afgesloten
            koppeling_nvt: Koppeling n.v.t.

        Persoontypen:
            Klant: Klanten
            Vrijwilliger: Vrijwilligers

        Werkgebieden:
            "": ""
            "Amstelveen": "Amstelveen"
            "Centrum": "Centrum"
            "Diemen": "Diemen"
            "Nieuw-West": "Nieuw-West"
            "Noord": "Noord"
            "Overig": "Overig"
            "Oost": "Oost"
            "West": "West"
            "Westpoort": "Westpoort"
            "Zuid": "Zuid"
            "Zuidoost": "Zuidoost"

        Postcodegebieden:
            "": ""
            "Noord-oost": "Noord-oost"
            "Noord-West": "Noord-West"
            "Oud Noord": "Oud Noord"
            "Westerpark": "Westerpark"
            "Centrum West": "Centrum West"
            "Centrum Oost": "Centrum Oost"
            "Oostelijke Havengebied - Indische Buurt": "Oostelijke Havengebied - Indische Buurt"
            "Oud Oost": "Oud Oost"
            "Ijburg - Zeeburgereiland": "Ijburg - Zeeburgereiland"
            "Watergraafsmeer": "Watergraafsmeer"
            "De Pijp - Rivierenbuurt": "De Pijp - Rivierenbuurt"
            "Buitenveldert - Zuidas": "Buitenveldert - Zuidas"
            "Zuid": "Zuid"
            "De Baarsjes - Oud West": "De Baarsjes - Oud West"
            "Bos en Lommer": "Bos en Lommer"
            "Geuzenveld - Slotermeer": "Geuzenveld - Slotermeer"
            "Slotervaart": "Slotervaart"
            "Osdorp": "Osdorp"
            "De Aker - Nieuw Sloten": "De Aker - Nieuw Sloten"
            "Bijlmer Centrum": "Bijlmer Centrum"
            "Bijlmer Oost": "Bijlmer Oost"
            "Gaaperdam - Driemond": "Gaaperdam - Driemond"
            "Overig": "Overig"

        Afmeldstatus:
            "": ""
            "Aanwezig": "Aanwezig"
            "Afwezig": "Afwezig"

services:
    cake.service.config:
        class: CakeBundle\Service\CakeConfiguration

    cake.service.cache_warmer:
        class: CakeBundle\Service\CakeCacheWarmer
        tags:
            - { name: kernel.cache_warmer, priority: 100 }

    cake.event.controller:
        class: CakeBundle\Event\KernelSubscriber
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_subscriber }
