hs_annotations:
    resource: "@HsBundle/Controller"
    type: annotation

hs_index:
    path: /hs
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: hs_klanten_index
