imports:
    - { resource: exports.yml }

services:
    odp.event.diensten_lookup_subscriber:
        class: OdpBundle\Event\DienstenLookupSubscriber
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    odp.data_fixtures.faker_provider:
        class: OdpBundle\DataFixtures\OdpFakerProvider
        tags:
            - { name: hautelook_alice.faker.provider }

    odp.dao:
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@knp_paginator'
            - '%pagination.items_per_page%'

    odp.dao.coordinator:
        parent: odp.dao
        class: OdpBundle\Service\CoordinatorDao

    odp.dao.document:
        class: OdpBundle\Service\DocumentDao
        arguments:
            - '@doctrine.orm.entity_manager'

    odp.dao.huuraanbodafsluiting:
        parent: odp.dao
        class: OdpBundle\Service\HuuraanbodAfsluitingDao

    odp.dao.huurderafsluiting:
        parent: odp.dao
        class: OdpBundle\Service\HuurderAfsluitingDao

    odp.dao.huurovereenkomstafsluiting:
        parent: odp.dao
        class: OdpBundle\Service\HuurovereenkomstAfsluitingDao

    odp.dao.huurverzoekafsluiting:
        parent: odp.dao
        class: OdpBundle\Service\HuurverzoekAfsluitingDao

    odp.dao.verhuurderafsluiting:
        parent: odp.dao
        class: OdpBundle\Service\VerhuurderAfsluitingDao

    odp.dao.verslag:
        class: OdpBundle\Service\VerslagDao
        arguments:
            - '@doctrine.orm.entity_manager'

    odp.dao.woningbouwcorporatie:
        parent: odp.dao
        class: OdpBundle\Service\WoningbouwcorporatieDao
